packages:
  - "."
  - "src/Kentico.Community.Portal.Web"
  - "src/Kentico.Community.Portal.Admin/Client"
  - "test/kentico-community-portal-web-e2e-tests"

minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
allowBuilds:
  "@parcel/watcher": true
minimumReleaseAgeExclude:
  - "@eslint/eslintrc@3.3.6"
  - "@milkdown/components@7.21.3"
  - "@milkdown/core@7.21.3"
  - "@milkdown/crepe@7.21.3"
  - "@milkdown/ctx@7.21.3"
  - "@milkdown/exception@7.21.3"
  - "@milkdown/kit@7.21.3"
  - "@milkdown/plugin-block@7.21.3"
  - "@milkdown/plugin-clipboard@7.21.3"
  - "@milkdown/plugin-cursor@7.21.3"
  - "@milkdown/plugin-diff@7.21.3"
  - "@milkdown/plugin-history@7.21.3"
  - "@milkdown/plugin-indent@7.21.3"
  - "@milkdown/plugin-listener@7.21.3"
  - "@milkdown/plugin-slash@7.21.3"
  - "@milkdown/plugin-streaming@7.21.3"
  - "@milkdown/plugin-tooltip@7.21.3"
  - "@milkdown/plugin-trailing@7.21.3"
  - "@milkdown/plugin-upload@7.21.3"
  - "@milkdown/preset-commonmark@7.21.3"
  - "@milkdown/preset-gfm@7.21.3"
  - "@milkdown/prose@7.21.3"
  - "@milkdown/react@7.21.3"
  - "@milkdown/transformer@7.21.3"
  - "@milkdown/utils@7.21.3"
