//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.EmailLibrary;
using Kentico.Community.Portal.Core.Content;

namespace Kentico.Community.Portal.Core.Emails
{
	/// <summary>
	/// Represents an email of type <see cref="NewsletterEmail"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class NewsletterEmail : IEmailFieldsSource, IEmailDesignFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.NewsletterEmail";


		/// <summary>
		/// Represents system properties for an email item.
		/// </summary>
		[SystemField]
		public EmailFields SystemFields { get; set; }


		/// <summary>
		/// EmailSubject.
		/// </summary>
		public string EmailSubject { get; set; }


		/// <summary>
		/// EmailPreviewText.
		/// </summary>
		public string EmailPreviewText { get; set; }


		/// <summary>
		/// NewsletterEmailTitle.
		/// </summary>
		public string NewsletterEmailTitle { get; set; }


		/// <summary>
		/// NewsletterEmailIssueNumber.
		/// </summary>
		public string NewsletterEmailIssueNumber { get; set; }


		/// <summary>
		/// NewsletterEmailPublishedDate.
		/// </summary>
		public DateTime NewsletterEmailPublishedDate { get; set; }


		/// <summary>
		/// NewsletterEmailIntroContentHTML.
		/// </summary>
		public string NewsletterEmailIntroContentHTML { get; set; }


		/// <summary>
		/// NewsletterEmailBlogPostPages.
		/// </summary>
		public IEnumerable<BlogPostPage> NewsletterEmailBlogPostPages { get; set; }


		/// <summary>
		/// NewsletterEmailLinkContents.
		/// </summary>
		public IEnumerable<LinkContent> NewsletterEmailLinkContents { get; set; }


		/// <summary>
		/// NewsletterEmailQAndADiscussionPages.
		/// </summary>
		public IEnumerable<QAndAQuestionPage> NewsletterEmailQAndADiscussionPages { get; set; }


		/// <summary>
		/// NewsletterEmailOutroContentHTML.
		/// </summary>
		public string NewsletterEmailOutroContentHTML { get; set; }


		/// <summary>
		/// NewsletterEmailUTMParameters.
		/// </summary>
		public UTMParametersDataType NewsletterEmailUTMParameters { get; set; }


		/// <summary>
		/// EmailDesignEmailDefaultsContent.
		/// </summary>
		public IEnumerable<EmailDefaultsContent> EmailDesignEmailDefaultsContent { get; set; }
	}
}