//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using Kentico.Community.Portal.Core.Forms;

[assembly: RegisterBizForm(Poll_20250212_MostDifficultProjectStepItem.CLASS_NAME, typeof(Poll_20250212_MostDifficultProjectStepItem))]

namespace Kentico.Community.Portal.Core.Forms
{
	/// <summary>
	/// Represents a content item of type Poll_20250212_MostDifficultProjectStepItem.
	/// </summary>
	public partial class Poll_20250212_MostDifficultProjectStepItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.Poll_20250212_MostDifficultProjectStep";


		/// <summary>
		/// The instance of the class that provides extended API for working with Poll_20250212_MostDifficultProjectStepItem fields.
		/// </summary>
		private readonly Poll_20250212_MostDifficultProjectStepItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MemberID.
		/// </summary>
		[DatabaseField]
		public int MemberID
		{
			get => ValidationHelper.GetInteger(GetValue(nameof(MemberID)), 0);
			set => SetValue(nameof(MemberID), value);
		}


		/// <summary>
		/// Question.
		/// </summary>
		[DatabaseField]
		public string Question
		{
			get => ValidationHelper.GetString(GetValue(nameof(Question)), @"");
			set => SetValue(nameof(Question), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Poll_20250212_MostDifficultProjectStepItem fields.
		/// </summary>
		[RegisterProperty]
		public Poll_20250212_MostDifficultProjectStepItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with Poll_20250212_MostDifficultProjectStepItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class Poll_20250212_MostDifficultProjectStepItemFields : AbstractHierarchicalObject<Poll_20250212_MostDifficultProjectStepItemFields>
		{
			/// <summary>
			/// The content item of type Poll_20250212_MostDifficultProjectStepItem that is a target of the extended API.
			/// </summary>
			private readonly Poll_20250212_MostDifficultProjectStepItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="Poll_20250212_MostDifficultProjectStepItemFields" /> class with the specified content item of type Poll_20250212_MostDifficultProjectStepItem.
			/// </summary>
			/// <param name="instance">The content item of type Poll_20250212_MostDifficultProjectStepItem that is a target of the extended API.</param>
			public Poll_20250212_MostDifficultProjectStepItemFields(Poll_20250212_MostDifficultProjectStepItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MemberID.
			/// </summary>
			public int MemberID
			{
				get => mInstance.MemberID;
				set => mInstance.MemberID = value;
			}


			/// <summary>
			/// Question.
			/// </summary>
			public string Question
			{
				get => mInstance.Question;
				set => mInstance.Question = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Poll_20250212_MostDifficultProjectStepItem" /> class.
		/// </summary>
		public Poll_20250212_MostDifficultProjectStepItem() : base(CLASS_NAME)
		{
			mFields = new Poll_20250212_MostDifficultProjectStepItemFields(this);
		}

		#endregion
	}
}