//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using Kentico.Community.Portal.Core.Forms;

[assembly: RegisterBizForm(CommunityFeedbackFormItem.CLASS_NAME, typeof(CommunityFeedbackFormItem))]

namespace Kentico.Community.Portal.Core.Forms
{
	/// <summary>
	/// Represents a content item of type CommunityFeedbackFormItem.
	/// </summary>
	public partial class CommunityFeedbackFormItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.CommunityFeedbackForm";


		/// <summary>
		/// The instance of the class that provides extended API for working with CommunityFeedbackFormItem fields.
		/// </summary>
		private readonly CommunityFeedbackFormItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// FirstName.
		/// </summary>
		[DatabaseField]
		public string FirstName
		{
			get => ValidationHelper.GetString(GetValue(nameof(FirstName)), @"");
			set => SetValue(nameof(FirstName), value);
		}


		/// <summary>
		/// LastName.
		/// </summary>
		[DatabaseField]
		public string LastName
		{
			get => ValidationHelper.GetString(GetValue(nameof(LastName)), @"");
			set => SetValue(nameof(LastName), value);
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get => ValidationHelper.GetString(GetValue(nameof(Email)), @"");
			set => SetValue(nameof(Email), value);
		}


		/// <summary>
		/// Feedback.
		/// </summary>
		[DatabaseField]
		public string Feedback
		{
			get => ValidationHelper.GetString(GetValue(nameof(Feedback)), @"");
			set => SetValue(nameof(Feedback), value);
		}


		/// <summary>
		/// Recaptcha_FormComponent.
		/// </summary>
		[DatabaseField]
		public string Recaptcha_FormComponent
		{
			get => ValidationHelper.GetString(GetValue(nameof(Recaptcha_FormComponent)), @"");
			set => SetValue(nameof(Recaptcha_FormComponent), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CommunityFeedbackFormItem fields.
		/// </summary>
		[RegisterProperty]
		public CommunityFeedbackFormItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with CommunityFeedbackFormItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CommunityFeedbackFormItemFields : AbstractHierarchicalObject<CommunityFeedbackFormItemFields>
		{
			/// <summary>
			/// The content item of type CommunityFeedbackFormItem that is a target of the extended API.
			/// </summary>
			private readonly CommunityFeedbackFormItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CommunityFeedbackFormItemFields" /> class with the specified content item of type CommunityFeedbackFormItem.
			/// </summary>
			/// <param name="instance">The content item of type CommunityFeedbackFormItem that is a target of the extended API.</param>
			public CommunityFeedbackFormItemFields(CommunityFeedbackFormItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// FirstName.
			/// </summary>
			public string FirstName
			{
				get => mInstance.FirstName;
				set => mInstance.FirstName = value;
			}


			/// <summary>
			/// LastName.
			/// </summary>
			public string LastName
			{
				get => mInstance.LastName;
				set => mInstance.LastName = value;
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get => mInstance.Email;
				set => mInstance.Email = value;
			}


			/// <summary>
			/// Feedback.
			/// </summary>
			public string Feedback
			{
				get => mInstance.Feedback;
				set => mInstance.Feedback = value;
			}


			/// <summary>
			/// Recaptcha_FormComponent.
			/// </summary>
			public string Recaptcha_FormComponent
			{
				get => mInstance.Recaptcha_FormComponent;
				set => mInstance.Recaptcha_FormComponent = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CommunityFeedbackFormItem" /> class.
		/// </summary>
		public CommunityFeedbackFormItem() : base(CLASS_NAME)
		{
			mFields = new CommunityFeedbackFormItemFields(this);
		}

		#endregion
	}
}