//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using Kentico.Community.Portal.Core.Forms;

[assembly: RegisterBizForm(CommunityProgramInterestItem.CLASS_NAME, typeof(CommunityProgramInterestItem))]

namespace Kentico.Community.Portal.Core.Forms
{
	/// <summary>
	/// Represents a content item of type CommunityProgramInterestItem.
	/// </summary>
	public partial class CommunityProgramInterestItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.CommunityProgramInterest";


		/// <summary>
		/// The instance of the class that provides extended API for working with CommunityProgramInterestItem fields.
		/// </summary>
		private readonly CommunityProgramInterestItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MemberID.
		/// </summary>
		[DatabaseField]
		public int MemberID
		{
			get => ValidationHelper.GetInteger(GetValue(nameof(MemberID)), 0);
			set => SetValue(nameof(MemberID), value);
		}


		/// <summary>
		/// MemberEmail.
		/// </summary>
		[DatabaseField]
		public string MemberEmail
		{
			get => ValidationHelper.GetString(GetValue(nameof(MemberEmail)), @"");
			set => SetValue(nameof(MemberEmail), value);
		}


		/// <summary>
		/// Program.
		/// </summary>
		[DatabaseField]
		public string Program
		{
			get => ValidationHelper.GetString(GetValue(nameof(Program)), @"");
			set => SetValue(nameof(Program), value);
		}


		/// <summary>
		/// Motivation.
		/// </summary>
		[DatabaseField]
		public string Motivation
		{
			get => ValidationHelper.GetString(GetValue(nameof(Motivation)), @"");
			set => SetValue(nameof(Motivation), value);
		}


		/// <summary>
		/// ActivityExamples.
		/// </summary>
		[DatabaseField]
		public string ActivityExamples
		{
			get => ValidationHelper.GetString(GetValue(nameof(ActivityExamples)), @"");
			set => SetValue(nameof(ActivityExamples), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CommunityProgramInterestItem fields.
		/// </summary>
		[RegisterProperty]
		public CommunityProgramInterestItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with CommunityProgramInterestItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CommunityProgramInterestItemFields : AbstractHierarchicalObject<CommunityProgramInterestItemFields>
		{
			/// <summary>
			/// The content item of type CommunityProgramInterestItem that is a target of the extended API.
			/// </summary>
			private readonly CommunityProgramInterestItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CommunityProgramInterestItemFields" /> class with the specified content item of type CommunityProgramInterestItem.
			/// </summary>
			/// <param name="instance">The content item of type CommunityProgramInterestItem that is a target of the extended API.</param>
			public CommunityProgramInterestItemFields(CommunityProgramInterestItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MemberID.
			/// </summary>
			public int MemberID
			{
				get => mInstance.MemberID;
				set => mInstance.MemberID = value;
			}


			/// <summary>
			/// MemberEmail.
			/// </summary>
			public string MemberEmail
			{
				get => mInstance.MemberEmail;
				set => mInstance.MemberEmail = value;
			}


			/// <summary>
			/// Program.
			/// </summary>
			public string Program
			{
				get => mInstance.Program;
				set => mInstance.Program = value;
			}


			/// <summary>
			/// Motivation.
			/// </summary>
			public string Motivation
			{
				get => mInstance.Motivation;
				set => mInstance.Motivation = value;
			}


			/// <summary>
			/// ActivityExamples.
			/// </summary>
			public string ActivityExamples
			{
				get => mInstance.ActivityExamples;
				set => mInstance.ActivityExamples = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CommunityProgramInterestItem" /> class.
		/// </summary>
		public CommunityProgramInterestItem() : base(CLASS_NAME)
		{
			mFields = new CommunityProgramInterestItemFields(this);
		}

		#endregion
	}
}