//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.Websites;
using CMS.MediaLibrary;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a page of type <see cref="BlogPostPage"/>.
	/// </summary>
	public partial class BlogPostPage : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.BlogPostPage";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// BlogPostPageTitle.
		/// </summary>
		public string BlogPostPageTitle { get; set; }


		/// <summary>
		/// BlogPostPageBlogPostContent.
		/// </summary>
		public IEnumerable<BlogPostContent> BlogPostPageBlogPostContent { get; set; }


		/// <summary>
		/// BlogPostPageAuthor.
		/// </summary>
		public IEnumerable<AuthorContent> BlogPostPageAuthor { get; set; }


		/// <summary>
		/// BlogPostPageTeaserMediaFileImage.
		/// </summary>
		public IEnumerable<AssetRelatedItem> BlogPostPageTeaserMediaFileImage { get; set; }


		/// <summary>
		/// BlogPostPageShortDescription.
		/// </summary>
		public string BlogPostPageShortDescription { get; set; }


		/// <summary>
		/// BlogPostPageTaxonomy.
		/// </summary>
		public string BlogPostPageTaxonomy { get; set; }


		/// <summary>
		/// BlogPostPageDate.
		/// </summary>
		public DateTime BlogPostPageDate { get; set; }


		/// <summary>
		/// BlogPostPageContentType.
		/// </summary>
		public string BlogPostPageContentType { get; set; }


		/// <summary>
		/// BlogPostPageContentMarkdown.
		/// </summary>
		public string BlogPostPageContentMarkdown { get; set; }


		/// <summary>
		/// BlogPostPageContentHTML.
		/// </summary>
		public string BlogPostPageContentHTML { get; set; }
	}
}