//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.Websites;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a page of type <see cref="RSSFeedPage"/>.
	/// </summary>
	public partial class RSSFeedPage : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.RSSFeedPage";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// RSSFeedPageFeedName.
		/// </summary>
		public string RSSFeedPageFeedName { get; set; }


		/// <summary>
		/// RSSFeedPageFeedShortDescription.
		/// </summary>
		public string RSSFeedPageFeedShortDescription { get; set; }


		/// <summary>
		/// RSSFeedPageWebPageContentType.
		/// </summary>
		public string RSSFeedPageWebPageContentType { get; set; }


		/// <summary>
		/// RSSFeedPageItemsLimit.
		/// </summary>
		public int RSSFeedPageItemsLimit { get; set; }
	}
}