//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.Websites;
using CMS.MediaLibrary;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a page of type <see cref="WebsiteSettingsContent"/>.
	/// </summary>
	public partial class WebsiteSettingsContent : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.WebsiteSettingsContent";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// WebsiteSettingsContentWebsiteDisplayName.
		/// </summary>
		public string WebsiteSettingsContentWebsiteDisplayName { get; set; }


		/// <summary>
		/// WebsiteSettingsContentPageTitleFormat.
		/// </summary>
		public string WebsiteSettingsContentPageTitleFormat { get; set; }


		/// <summary>
		/// WebsiteSettingsContentFallbackOGMediaFileImage.
		/// </summary>
		public IEnumerable<AssetRelatedItem> WebsiteSettingsContentFallbackOGMediaFileImage { get; set; }


		/// <summary>
		/// WebsiteSettingsContentNotFoundContentHTML.
		/// </summary>
		public string WebsiteSettingsContentNotFoundContentHTML { get; set; }


		/// <summary>
		/// WebsiteSettingsContentExceptionContentHTML.
		/// </summary>
		public string WebsiteSettingsContentExceptionContentHTML { get; set; }


		/// <summary>
		/// WebsiteSettingsContentRobotsTxt.
		/// </summary>
		public string WebsiteSettingsContentRobotsTxt { get; set; }


		/// <summary>
		/// WebsiteSettingsContentCookieBannerHeading.
		/// </summary>
		public string WebsiteSettingsContentCookieBannerHeading { get; set; }


		/// <summary>
		/// WebsiteSettingsContentCookiebannerContentHTML.
		/// </summary>
		public string WebsiteSettingsContentCookiebannerContentHTML { get; set; }


		/// <summary>
		/// WebsiteSettingsContentIsAlertBoxEnabled.
		/// </summary>
		public bool WebsiteSettingsContentIsAlertBoxEnabled { get; set; }


		/// <summary>
		/// WebsiteSettingsContentAlertBoxCookieExpirationDays.
		/// </summary>
		public int WebsiteSettingsContentAlertBoxCookieExpirationDays { get; set; }


		/// <summary>
		/// WebsiteSettingsContentAlertBoxContentHTML.
		/// </summary>
		public string WebsiteSettingsContentAlertBoxContentHTML { get; set; }


		/// <summary>
		/// WebsiteSettingsContentFormsConfigurationJSON.
		/// </summary>
		public string WebsiteSettingsContentFormsConfigurationJSON { get; set; }
	}
}