//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using Kentico.Community.Portal.Core.Content;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="CardContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class CardContent : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.CardContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// CardContentWebpage.
		/// </summary>
		public IEnumerable<WebPageRelatedItem> CardContentWebpage { get; set; }


		/// <summary>
		/// CardContentListableItem.
		/// </summary>
		public IEnumerable<IFeaturedImageFields> CardContentListableItem { get; set; }


		/// <summary>
		/// CardContentTitle.
		/// </summary>
		public string CardContentTitle { get; set; }


		/// <summary>
		/// CardContentLabel.
		/// </summary>
		public string CardContentLabel { get; set; }


		/// <summary>
		/// CardContentUTMParameters.
		/// </summary>
		public UTMParametersDataType CardContentUTMParameters { get; set; }
	}
}