//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="FAQItemContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class FAQItemContent : IContentItemFieldsSource, ICoreTaxonomyFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.FAQItemContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// FAQItemContentQuestion.
		/// </summary>
		public string FAQItemContentQuestion { get; set; }


		/// <summary>
		/// FAQItemContentAnswerMarkdown.
		/// </summary>
		public string FAQItemContentAnswerMarkdown { get; set; }


		/// <summary>
		/// CoreTaxonomyDXTopics.
		/// </summary>
		public IEnumerable<TagReference> CoreTaxonomyDXTopics { get; set; }
	}
}