//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IListableItem"/> reusable schema assigned.
	/// </summary>
	public interface IListableItem
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "ListableItem";


		/// <summary>
		/// ListableItemTitle.
		/// </summary>
		public string ListableItemTitle { get; set; }


		/// <summary>
		/// ListableItemShortDescription.
		/// </summary>
		public string ListableItemShortDescription { get; set; }


		/// <summary>
		/// ListableItemFeaturedImageContent.
		/// </summary>
		public IEnumerable<ImageContent> ListableItemFeaturedImageContent { get; set; }


		/// <summary>
		/// ListableItemFeaturedImage.
		/// </summary>
		public IEnumerable<MediaAssetContent> ListableItemFeaturedImage { get; set; }
	}
}