//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IWebPageMetaFields"/> reusable schema assigned.
	/// </summary>
	public interface IWebPageMetaFields
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "WebPageMetaFields";


		/// <summary>
		/// WebPageMetaTitle.
		/// </summary>
		public string WebPageMetaTitle { get; set; }


		/// <summary>
		/// WebPageMetaShortDescription.
		/// </summary>
		public string WebPageMetaShortDescription { get; set; }


		/// <summary>
		/// WebPageMetaExcludeFromSitemap.
		/// </summary>
		public bool WebPageMetaExcludeFromSitemap { get; set; }


		/// <summary>
		/// WebPageMetaRobots.
		/// </summary>
		public string WebPageMetaRobots { get; set; }


		/// <summary>
		/// WebPageCanonicalURL.
		/// </summary>
		public string WebPageCanonicalURL { get; set; }
	}
}