//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="LinkContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class LinkContent : IContentItemFieldsSource, IBasicItemFields, ICoreTaxonomyFields
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.LinkContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// LinkContentLabel.
		/// </summary>
		public string LinkContentLabel { get; set; }


		/// <summary>
		/// LinkContentPathOrURL.
		/// </summary>
		public string LinkContentPathOrURL { get; set; }


		/// <summary>
		/// LinkContentShortDescription.
		/// </summary>
		public string LinkContentShortDescription { get; set; }


		/// <summary>
		/// LinkContentPublishedDate.
		/// </summary>
		public DateTime LinkContentPublishedDate { get; set; }


		/// <summary>
		/// LinkContentLinkType.
		/// </summary>
		public string LinkContentLinkType { get; set; }


		/// <summary>
		/// LinkContentDXTopics.
		/// </summary>
		public IEnumerable<TagReference> LinkContentDXTopics { get; set; }


		/// <summary>
		/// LinkContentMemberID.
		/// </summary>
		public int LinkContentMemberID { get; set; }


		/// <summary>
		/// BasicItemTitle.
		/// </summary>
		public string BasicItemTitle { get; set; }


		/// <summary>
		/// BasicItemShortDescription.
		/// </summary>
		public string BasicItemShortDescription { get; set; }


		/// <summary>
		/// CoreTaxonomyDXTopics.
		/// </summary>
		public IEnumerable<TagReference> CoreTaxonomyDXTopics { get; set; }
	}
}