//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="LinkContent"/>.
	/// </summary>
	public partial class LinkContent
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.LinkContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// DocumentName.
		/// </summary>
		public string DocumentName { get; set; }


		/// <summary>
		/// LinkContentLabel.
		/// </summary>
		public string LinkContentLabel { get; set; }


		/// <summary>
		/// LinkContentPathOrURL.
		/// </summary>
		public string LinkContentPathOrURL { get; set; }


		/// <summary>
		/// LinkContentShortDescription.
		/// </summary>
		public string LinkContentShortDescription { get; set; }
	}
}