//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="MemberProfileContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class MemberProfileContent : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.MemberProfileContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// MemberProfileContentFullName.
		/// </summary>
		public string MemberProfileContentFullName { get; set; }


		/// <summary>
		/// MemberProfileContentPhotoImageContent.
		/// </summary>
		public IEnumerable<ImageContent> MemberProfileContentPhotoImageContent { get; set; }


		/// <summary>
		/// MemberProfileContentMemberID.
		/// </summary>
		public int MemberProfileContentMemberID { get; set; }
	}
}