//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="PollContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class PollContent : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.PollContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// PollContentForm.
		/// </summary>
		public IEnumerable<string> PollContentForm { get; set; }


		/// <summary>
		/// PollContentDescriptionMarkdown.
		/// </summary>
		public string PollContentDescriptionMarkdown { get; set; }


		/// <summary>
		/// PollContentDXTopics.
		/// </summary>
		public IEnumerable<TagReference> PollContentDXTopics { get; set; }


		/// <summary>
		/// PollContentPublishedDate.
		/// </summary>
		public DateTime PollContentPublishedDate { get; set; }


		/// <summary>
		/// PollContentOpenUntilDate.
		/// </summary>
		public DateTime PollContentOpenUntilDate { get; set; }
	}
}