//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="TestimonialContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class TestimonialContent : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.TestimonialContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// TestimonialContentTitle.
		/// </summary>
		public string TestimonialContentTitle { get; set; }


		/// <summary>
		/// TestimonialContentMessage.
		/// </summary>
		public string TestimonialContentMessage { get; set; }


		/// <summary>
		/// TestimonialContentDataSource.
		/// </summary>
		public string TestimonialContentDataSource { get; set; }


		/// <summary>
		/// TestimonialContentMemberID.
		/// </summary>
		public int TestimonialContentMemberID { get; set; }


		/// <summary>
		/// TestimonialContentPhoto.
		/// </summary>
		public IEnumerable<ImageContent> TestimonialContentPhoto { get; set; }


		/// <summary>
		/// TestimonialContentName.
		/// </summary>
		public string TestimonialContentName { get; set; }


		/// <summary>
		/// TestimonialContentJobTitle.
		/// </summary>
		public string TestimonialContentJobTitle { get; set; }


		/// <summary>
		/// TestimonialContentEmployer.
		/// </summary>
		public string TestimonialContentEmployer { get; set; }
	}
}