//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="VideoContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class VideoContent : IContentItemFieldsSource, IMediaItem
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.VideoContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// VideoContentAsset.
		/// </summary>
		public ContentItemAsset VideoContentAsset { get; set; }


		/// <summary>
		/// MediaItemTitle.
		/// </summary>
		public string MediaItemTitle { get; set; }


		/// <summary>
		/// MediaItemShortDescription.
		/// </summary>
		public string MediaItemShortDescription { get; set; }


		/// <summary>
		/// MediaItemTaxonomy.
		/// </summary>
		public IEnumerable<TagReference> MediaItemTaxonomy { get; set; }


		/// <summary>
		/// MediaItemAssetWidth.
		/// </summary>
		public int MediaItemAssetWidth { get; set; }


		/// <summary>
		/// MediaItemAssetHeight.
		/// </summary>
		public int MediaItemAssetHeight { get; set; }
	}
}