//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Kentico.Community.Portal.Core.Content
{
	/// <summary>
	/// Represents a content item of type <see cref="WebsiteCookieBannerSettingsContent"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class WebsiteCookieBannerSettingsContent : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "KenticoCommunity.WebsiteCookieBannerSettingsContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// WebsiteCookieBannerSettingsContentHeading.
		/// </summary>
		public string WebsiteCookieBannerSettingsContentHeading { get; set; }


		/// <summary>
		/// WebsiteCookieBannerSettingsContentMessageHTML.
		/// </summary>
		public string WebsiteCookieBannerSettingsContentMessageHTML { get; set; }
	}
}